package Engine;

public enum CheckerType
{
    EMAIL_CHECKER,
    MIN_CHECKER,
    MAX_CHECKER,
    LENGTH_CHECKER,
    NEGATIVE_CHECKER,
    POSITIVE_CHECKER,
    NEGATIVE_OR_ZERO_CHECKER,
    POSITIVE_OR_ZERO_CHECKER,
    NOT_BLANK_CHECKER,
    NOT_EMPTY_CHECKER,
    NOT_NULL_CHECKER,
    NULL_CHECKER,
    REGEX_CHECKER
}